name: Android CI

on: [push, pull_request]

jobs:
  check_commit_hooks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Run pre-commit check
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: app/build/test-results/testDebugUnitTest/TEST-*.xml
          check_name: JUnit Test Report
      - name: Check notice file
        run: ./gradlew checkUpdatedLicenseFile
      - name: Archive debug apk
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            app/build/reports/licenses/*.html
            app/build/reports/*.html
